---
# handlers file for alloy
- name: Restart alloy
  listen: "restart alloy"
  ansible.builtin.systemd:
    daemon_reload: true
    name: alloy.service
    state: restarted
    enabled: true
  when: not ansible_check_mode and ansible_facts['os_family'] != 'Windows'

- name: Restart alloy on windows
  ansible.windows.win_service:
    name: alloy
    state: restarted
  when: ansible_facts['os_family'] == 'Windows'